coworking/authapp/urls.py
from django.contrib import admin
from django.urls import path
from authapp.views import login, user_logout, UserRegisterView, choose_type, landlord_register, verify

app_name = 'authapp'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', user_logout, name='logout'),
    path('choose/', choose_type, name='choose_type'),
    path('user/', UserRegisterView.as_view(), name='user'),
    path('landlord/', landlord_register, name='landlord'),
    path('verify/<email>/<activation_key>/', verify, name='verify'),
]

coworking/detailsapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from detailsapp.views import show_details, create_rental, add_favorite, send_review, get_available_seats, del_favorite

urlpatterns = [
    path('<int:pk>/', show_details, name='details'),
    path('add_fav/<int:pk>/', add_favorite, name='add_favorite'),
    path('del_fav/<int:pk>/', del_favorite, name='del_favorite'),
    path('new_rent/<int:pk>/', create_rental, name='create_rental'),
    path('review/<int:pk>/', send_review, name='send_review'),
    path('<int:pk>/<str:start_date>/<str:end_date>/<int:seats>/',
         get_available_seats, name='get_seats')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coworking/mainapp/urls.py
from django.contrib import admin
from django.urls import path, include
from mainapp.views import main
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main, name='main'),
    path('user/', include(('userapp.urls', 'userapp'), namespace='user')),
    path('auth/', include(('authapp.urls', 'authapp'), namespace='auth')),
    path('offers/', include(('offersapp.urls', 'offersapp'), namespace='offers')),
    path('details/', include(('detailsapp.urls', 'detailsapp'), namespace='details')),
    path('feedback/', include(('feedbackapp.urls', 'feedbackapp'), namespace='feedback')),
    path('admin_staff/', include(('adminapp.urls', 'adminapp'), namespace='admin_staff')),
    path('create/', include(('createapp.urls', 'createapp'), namespace='create')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coworking/offersapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
# from django.contrib import admin
from django.urls import path

# from offersapp.views import main, SearchResultsView, search_results
from offersapp.views import search_results

urlpatterns = [
    # path('', main, name='main'),
    path('search/', search_results, name='search_results'),
    path('search/page/<int:page>/', search_results, name='page'),
    # path('search/', SearchResultsView.as_view(), name='search_results'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coworking/userapp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import user, user_profile, user_bookings, user_favorites, user_locations, claim_landlord
from .views import booking_history, users, change_ad


app_name = 'userapp'

urlpatterns = [
    path('', user, name='main'),
    path('profile/', user_profile, name='profile'),
    path('bookings/', user_bookings, name='bookings'),
    path('locations/', user_locations, name='locations'),
    path('favorites/', user_favorites, name='favorites'),
    path('landlord-application/', claim_landlord, name='landlord-application'),
    path('booking-history/', booking_history, name='booking_history'),
    path('users/<int:pk>', users, name='users'),
    path('change-ad/<int:pk>', change_ad, name='change_ad'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coworking/offersapp/models.py
from django.db import models

# Create your models here.

coworking/offersapp/forms.py
from django import forms
from django.forms import ModelForm

from createapp.models import Room, RoomCategory, Address


class CreateSearchForm(ModelForm):
    name = forms.CharField(label="Наименование помещения",
                           initial='Room Name',
                           widget=forms.TextInput(attrs={'class': 'form-control py-2',
                                                         'placeholder': 'Наименование помещения'}))
    square = forms.FloatField(label="Площадь помещения",
                              initial=70,
                              widget=forms.TextInput(attrs={'placeholder': 'Площадь помещения'}))
    description = forms.CharField(label="Описание",
                                  initial="Description",
                                  widget=forms.Textarea(attrs={'class': 'form-control',
                                                               'placeholder': 'Описание',
                                                               'rows': 6}))

    payment_per_hour = forms.DecimalField(max_digits=10, initial=1000, decimal_places=2, label="Цена за час (руб.)",
                                          widget=forms.TextInput(attrs={'placeholder': 'Цена в час'}))

    category = forms.ModelChoiceField(label="Категория", queryset=RoomCategory.objects.all(),
                                      empty_label="Категория не выбрана")

    address = forms.CharField(label="Название помещения",
                              widget=forms.TextInput(
                                  attrs={'id': 'address', 'placeholder': 'Введите адрес', 'style': 'width: 100%'}))

    class Meta:
        model = Room
        fields = ['name', 'square', 'description', 'payment_per_hour', 'category', 'phone_number']

coworking/offersapp/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, reverse
from django.views.generic import ListView

from createapp.models import Room, OfferImages, Convenience, ConvenienceRoom, RoomCategory, Address
from detailsapp.models import OffersRatings, CurrentRentals
from .utils import create_url, get_response, validate_data

from datetime import datetime, timedelta, date
import json
from lxml import html


def get_yandex_news(dom):
    list_of_news = []
    news_list = dom.xpath("//div[contains(@class, 'mg-card_flexible')]")

    for news in news_list:
        news_info = {}

        name_of_the_news = news.xpath(".//a[@class='mg-card__link']/text()")
        news_link = news.xpath(".//a[@class='mg-card__link']/@href")
        news_date = news.xpath(".//span[@class='mg-card-source__time']/text()")
        news_annotation = news.xpath(".//div[@class='mg-card__annotation']/text()")
        news_source = news.xpath(".//a[@class='mg-card__source-link']/text()")
        news_image_link = news.xpath(".//img[contains(@class, 'neo-image')]/@src")
        if len(news_image_link) == 0:
            news_image_link = news.xpath(".//div[contains(@class, 'mg-card__media-block_type_image')]/@style")
            try:
                news_image_link = news_image_link[0]
                news_image_link = news_image_link[news_image_link.find('(') + 1:news_image_link.find(')')]
                news_info['image'] = news_image_link
            except:
                break
        else:
            news_info['image'] = news_image_link[0]

        news_info['source'] = news_source[0]
        news_info['name'] = validate_data(name_of_the_news[0])
        news_info['link'] = news_link[0]
        news_info['date'] = f'{date.today()}T{news_date[0]}+03:00'
        news_info['text'] = news_annotation[0]

        list_of_news.append(news_info)
    return list_of_news


def get_news_data(site):
    url = create_url(site)
    response = get_response(url)
    dom = html.fromstring(response.text)
    news_data = get_yandex_news(dom)

    return news_data


def get_offers(city=None):
    if city is None:
        return Room.objects.filter(
            is_active=True,
            is_published=True
        ).order_by('payment_per_hour')[:10]
    else:
        return Room.objects.filter(
            is_active=True,
            is_published=True,
            address__city=city
        )


def add_images_info(rooms):
    # offers_dict = {}
    for room in rooms:
        room_images = OfferImages.objects.filter(room=room)
        room_images = [_ for _ in room_images]
        rooms[room].update({'images': room_images})
        # offers_dict[room] = room_images
    return rooms


def add_ratings(rooms):
    rooms_dict = {}
    for room in rooms:
        room_rating_info = OffersRatings.objects.filter(
            Q(offer=room))
        room_rating_info = [_ for _ in room_rating_info]

        rooms_dict[room] = {'rating': room_rating_info}
    return rooms_dict


def filter_by_ratings(rooms, rating):
    rooms_dict = {}
    for room in rooms:
        room_rating_info = OffersRatings.objects.filter(
            Q(offer=room),
            Q(summary_rating__gte=rating))
        room_rating_info = [_ for _ in room_rating_info]
        if room_rating_info:
            rooms_dict[room] = {'rating': room_rating_info}
    return rooms_dict


def rental_time_in_range(search_start_date, search_end_date, rental_start_date, rental_end_date):
    """
    Функция, проверяющая, что даты аренды попадают в диапазон, указанный в поисковом запросе
    """
    if search_start_date <= rental_start_date <= search_end_date:
        return True
    elif search_start_date <= rental_end_date <= search_end_date:
        return True
    elif rental_start_date < search_start_date and search_end_date < rental_end_date:
        return True
    else:
        return False


def daterange(start_date, end_date):
    """
    Функция для итерации по диапазону дат
    p.s. try to use dateutil library
    https://overcoder.net/q/36175/%D0%B8%D1%82%D0%B5%D1%80%D0%B0%D1%86%D0%B8%D1%8F-%D0%BF%D0%BE-
    %D0%B4%D0%B8%D0%B0%D0%BF%D0%B0%D0%B7%D0%BE%D0%BD%D1%83-%D0%B4%D0%B0%D1%82-%D0%B2-python
    """
    for n in range(int((end_date - start_date).days) + 1):
        yield start_date + timedelta(n)


def count_seats_in_rentals_by_days(room_rentals, dates) -> dict:
    """
    Функция расчёта занятых мест в помещении по датам.
    room_rentals: список с арендами, даты которых попадают в поисковый диапазон
    dates: словарь с датами, указанными в поисковом запросе
    return: словарь в котором ключ - дата, значение - кол-во занятых мест
    """
    room_seats_by_days = dict()

    for current_rent in room_rentals:
        for rental_date in daterange(current_rent.start_date.date(), current_rent.end_date.date()):
            seats_count = 0
            if dates['date_from'] <= rental_date <= dates['date_to']:
                seats_count += current_rent.seats
                key = f'{rental_date}'
                if key in room_seats_by_days.keys():
                    room_seats_by_days[key] += seats_count
                else:
                    room_seats_by_days[key] = seats_count

    return room_seats_by_days


def check_that_room_has_free_seats(room, dates):
    """
    Функция проверки свободных мест в помещениях в указанном диапазоне дат.
    Возвращает True если есть свободные места. Иначе False
    """
    qs = CurrentRentals.objects.filter(
        Q(offer=room),
    )
    # temp = [_ for _ in qs]
    room_rentals = [_ for _ in qs if
                    rental_time_in_range(search_start_date=dates['date_from'],
                                         search_end_date=dates['date_to'],
                                         rental_start_date=_.start_date.date(),
                                         rental_end_date=_.end_date.date())]

    counted_seats_by_day = count_seats_in_rentals_by_days(room_rentals, dates)

    max_seats = room.seats_number
    for val in counted_seats_by_day.values():
        if val >= max_seats:
            return False

    return True


def filter_by_dates(rooms, dates):
    if dates:
        filtered_rooms_dict = dict()
        for room in rooms:
            if check_that_room_has_free_seats(room, dates):
                filtered_rooms_dict[room] = rooms[room]
        return filtered_rooms_dict
    else:
        return rooms


def get_actions():
    '''
    функция получения акций для посетителей
    '''
    actions = {
        'name': 'Скидка первым посетителям',
        'text': 'В июле первые 10 заказчиков получат скидку за аренду 25%',
    }
    return actions


def get_conveniences_name():
    conveniences = Convenience.objects.values('name')
    conv_names = []
    for elem in conveniences:
        conv_names.append(elem['name'])
    return conv_names


def get_categories_name():
    categories = RoomCategory.objects.values('name')
    cat_names = []
    for elem in categories:
        cat_names.append(elem['name'])
    return cat_names


def get_convenience_from_request(request):
    request_list = list(request)
    conv_names = get_conveniences_name()

    requested_conveniences = {}

    for elem in request_list:
        if elem in conv_names:
            conv = list(Convenience.objects.filter(name=elem))[0]
            requested_conveniences[elem] = conv.id

    return requested_conveniences


def get_categories_from_request(request):
    request_list = list(request)
    categories_names = get_categories_name()

    requested_categories = []

    for elem in request_list:
        if elem in categories_names:
            # category = RoomCategory.objects.filter(name=elem)
            # requested_categories[elem] = category.id
            requested_categories.append(elem)
    return requested_categories


def get_dates_from_request(request):
    requested_dates = dict()

    try:
        start_date = datetime.strptime(f"{request.get('date_from')}", "%Y-%m-%d").date()
    except ValueError:
        start_date = request.get('date_from')

    try:
        end_date = datetime.strptime(f"{request.get('date_to')}", "%Y-%m-%d").date()
    except ValueError:
        end_date = request.get('date_to')

    if start_date:
        requested_dates['date_from'] = start_date
    if end_date:
        requested_dates['date_to'] = end_date

    return requested_dates


def get_room_conveniences(room_with_convenience):
    room_conveniences = []
    for elem in room_with_convenience:
        room_conveniences.append(elem.convenience_id)

    return room_conveniences


def get_conveniences(offers: dict) -> dict:
    conveniences = Convenience.objects.all()
    conv_dict = dict()
    offers_keys = offers.keys()
    for conv in conveniences:
        conv_dict[conv.name] = 0
        for elem in offers_keys:
            convenience_room = ConvenienceRoom.objects.filter(convenience_id=conv.id, room_id=elem.id)
            if convenience_room:
                conv_dict[conv.name] += len(convenience_room)
    return conv_dict


def get_room_category(offers: dict) -> dict:
    categories = RoomCategory.objects.all()
    categories_dict = dict()
    offers_keys = offers.keys()
    for category in categories:
        categories_dict[category.name] = 0
        for elem in offers_keys:
            if Room.objects.filter(name=elem.name, category=category.id):
                categories_dict[category.name] += 1
    return categories_dict


def map_room_to_coords(room: Room) -> dict:
    address: Address = room.address
    return {
        'pk': room.pk,
        'name': room.name,
        'address': f"{address.city}, {address.street}, {address.building}",
        'lat': str(address.latitude),
        'lon': str(address.longitude)
    }


def calculate_coords(rooms: dict) -> str:

coworking/offersapp/templates/offersapp/includes/inc_card.html
<div class="card mb-3">
    <div class="row g-0">
        <div class="col-md-4">
            {% if room_info.images %}
            <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-inner">
                    {% for image in room_info.images %}
                    <div class="carousel-item {% if forloop.counter0 == 0 %}active{% endif %}">
                        <img src="/media/{{ image.image }}" class="d-block w-100" alt="...">
                    </div>
                    {% endfor %}
                </div>
            </div>
            {% else %}
            <img src="/media/no_image.jpg" class="d-block w-100" alt="...">
            {% endif %}
        </div>
        <div class="col-md-5">
            <div class="card-body">
                <a href="{% url 'details:details' room.pk %}" target="_blank">
                    <h5 class="card-title">{{ room.name }}</h5>

                    <p class="card-text"><span>{{ room.category.name }}</span></p>
                    <p class="card-text">Описание: {{ room.description }}</p>

                    <p class="card-text" id="address">{{ room.address.city }}, {{ room.address.street }},
                        {{ room.address.building }}</p>
                </a>
            </div>
        </div>
        <div class="col-md-2">
            <p class="card-text" style="position: absolute;top: 10px; font-size: small;">
                {% if room_info.rating.0.summary_rating %}
                Отзывов: {{ room_info.rating.0.reviews_number }}
                |
                Рейтинг: <strong>{{ room_info.rating.0.summary_rating }}</strong>
                {% endif %}
            </p>
            <span class="card-text" style="position: absolute;bottom: 10px;">{{ room.payment_per_hour }}
                                    &#8381 за час</span>
        </div>
    </div>
</div>

coworking/offersapp/templates/offersapp/includes/inc_footer.html
  <footer id="footer" class="footer">
    <div class="copyright">
      &copy; Copyright <strong><span>Location</span></strong>. All Rights Reserved
    </div>
  </footer><!-- End Footer -->

coworking/offersapp/templates/offersapp/includes/inc_header.html
{% load static %}
<header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
        <a href="{% url 'main' %}" class="logo d-flex align-items-center">
            <img src="{% static 'offersapp/assets/img/logo.png' %}" alt="">
            <span class="d-none d-lg-block">ЛОКАЦИЯ</span>
        </a>
        <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->

    <div class="search-bar">
        <form class="search-form d-flex align-items-center" id="citySearchForm" method="GET"
              action="{% url 'offers:search_results' %}">
            <input type="city_name_text" name="city" placeholder="Город" class="form-control" id="suggest"
                   value="{{ city|default:'' }}">
            <button type="submit" title="Search"><i class="bi bi-search"></i></button>
        </form>
    </div>
    <!-- End Search Bar -->

    {% if user.is_authenticated %}
    <nav class="header-nav ms-auto">
        <ul class="d-flex align-items-center">

            <li class="nav-item d-block d-lg-none">
                <a class="nav-link nav-icon search-bar-toggle " href="#">
                    <i class="bi bi-search"></i>
                </a>
            </li><!-- End Search Icon-->

            <li class="nav-item">
                <a href="{% url 'user:bookings' %}" class="nav-link" target="_blank">
                    <span class="d-none d-md-block ps-2">Мои бронирования</span>
                </a>
            </li>

            <li class="nav-item">
                <a href="{% url 'user:favorites' %}" class="nav-link" target="_blank">
                    <span class="d-none d-md-block ps-2">Избранное</span>
                </a>
            </li>

            {% if notifications in object_list%}
            <li class="nav-item dropdown">
                <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
                    <i class="bi bi-bell"></i>
                    <span class="badge bg-primary badge-number">4</span>
                </a><!-- End Notification Icon -->

                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow notifications">
                    <li class="dropdown-header">
                        У вас 4 новых уведомления
                        <a href="#"><span class="badge rounded-pill bg-primary p-2 ms-2">Посмотреть все</span></a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li class="notification-item">
                        <i class="bi bi-exclamation-circle text-warning"></i>
                        <div>
                            <h4>Lorem Ipsum</h4>
                            <p>Quae dolorem earum veritatis oditseno</p>
                            <p>30 min. ago</p>
                        </div>
                    </li>

                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li class="notification-item">
                        <i class="bi bi-x-circle text-danger"></i>
                        <div>
                            <h4>Atque rerum nesciunt</h4>
                            <p>Quae dolorem earum veritatis oditseno</p>
                            <p>1 hr. ago</p>
                        </div>
                    </li>

                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li class="notification-item">
                        <i class="bi bi-check-circle text-success"></i>
                        <div>
                            <h4>Sit rerum fuga</h4>
                            <p>Quae dolorem earum veritatis oditseno</p>
                            <p>2 hrs. ago</p>
                        </div>
                    </li>

                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li class="notification-item">
                        <i class="bi bi-info-circle text-primary"></i>
                        <div>
                            <h4>Dicta reprehenderit</h4>
                            <p>Quae dolorem earum veritatis oditseno</p>
                            <p>4 hrs. ago</p>
                        </div>
                    </li>

                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li class="dropdown-footer">
                        <a href="#">Показать все уведомления</a>
                    </li>

                </ul><!-- End Notification Dropdown Items -->

            </li><!-- End Notification Nav -->
            {% endif %}

            {% if message in object_list%}
            <li class="nav-item dropdown">

                <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
                    <i class="bi bi-chat-left-text"></i>
                    <span class="badge bg-success badge-number">2</span>
                </a><!-- End Messages Icon -->

                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow messages">
                    <li class="dropdown-header">
                        У вас 2 новых сообщения
                        <a href="#"><span class="badge rounded-pill bg-primary p-2 ms-2">Посмотреть все</span></a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li class="message-item">
                        <a href="#">
                            <img src="{% static 'offersapp/assets/img/messages-1.jpg' %}" alt="" class="rounded-circle">
                            <div>
                                <h4>Maria Hudson</h4>
                                <p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>
                                <p>4 hrs. ago</p>
                            </div>
                        </a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li class="message-item">
                        <a href="#">
                            <img src="{% static 'offersapp/assets/img/messages-2.jpg' %}" alt="" class="rounded-circle">
                            <div>
                                <h4>Anna Nelson</h4>
                                <p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>
                                <p>6 hrs. ago</p>
                            </div>
                        </a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li class="dropdown-footer">
                        <a href="#">Показать все сообщения</a>
                    </li>

                </ul><!-- End Messages Dropdown Items -->

            </li><!-- End Messages Nav -->
            {% endif %}
            <li class="nav-item">
                <a href="{% url 'user:profile' %}" class="nav-link" target="_blank">
                    <span class="d-none d-md-block ps-2">Личный кабинет</span>
                </a>
            </li>
<!--            <li class="nav-item dropdown pe-3">-->

<!--                <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">-->
<!--                    <img src="-->
<!--            {% if user.avatar %}-->
<!--            {{ user.avatar.url }}-->
<!--            {% else %}-->
<!--            {% static 'userapp/assets/img/profile-img.jpg' %}-->
<!--            {% endif %}" alt="Profile_foto" class="rounded-circle">-->
<!--                    <span class="d-none d-md-block dropdown-toggle ps-2">{{ user.get_full_name }}</span>-->
<!--                </a>&lt;!&ndash; End Profile Iamge Icon &ndash;&gt;-->

<!--                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">-->
<!--                    <li class="dropdown-header">-->
<!--                        <h6>{{ user.get_full_name }}</h6>-->
<!--                        <span>CEO</span>-->
<!--                    </li>-->
<!--                    <li>-->
<!--                        <hr class="dropdown-divider">-->
<!--                    </li>-->

<!--                    <li>-->
<!--                        <a class="dropdown-item d-flex align-items-center" href="{% url 'user:main' %}">-->
<!--                            <i class="bi bi-person"></i>-->
<!--                            <span>Мой профиль</span>-->
<!--                        </a>-->
<!--                    </li>-->
<!--                    <li>-->
<!--                        <hr class="dropdown-divider">-->
<!--                    </li>-->

<!--                    <li>-->
<!--                        <a class="dropdown-item d-flex align-items-center" href="{% url 'user:profile' %}">-->
<!--                            <i class="bi bi-gear"></i>-->
<!--                            <span>Настройки аккаунта</span>-->
<!--                        </a>-->
<!--                    </li>-->
<!--                    <li>-->
<!--                        <hr class="dropdown-divider">-->
<!--                    </li>-->

<!--                    <li>-->
<!--                        <a class="dropdown-item d-flex align-items-center" href="{% url 'feedback:main' %}">-->
<!--                            <i class="bi bi-question-circle"></i>-->
<!--                            <span>Нужна помощь?</span>-->
<!--                        </a>-->
<!--                    </li>-->
<!--                    <li>-->
<!--                        <hr class="dropdown-divider">-->
<!--                    </li>-->

<!--                    <li>-->
<!--                        <a class="dropdown-item d-flex align-items-center" href="{% url 'auth:logout' %}">-->
<!--                            <i class="bi bi-box-arrow-right"></i>-->
<!--                            <span>Выход</span>-->
<!--                        </a>-->
<!--                    </li>-->

<!--                </ul>&lt;!&ndash; End Profile Dropdown Items &ndash;&gt;-->
<!--            </li>-->
            <!-- End Profile Nav -->


        </ul>
    </nav><!-- End Icons Navigation -->
    {% else %}
    <nav class="header-nav ms-auto">
        <ul class="d-flex align-items-center">
            <a class="nav-link collapsed" href="{% url 'auth:login' %}">
                <i class="bi bi-box-arrow-in-right"></i>
                <span>Вход</span>
            </a>
        </ul>


        </ul>
    </nav><!-- End Icons Navigation -->
    {% endif %}

</header><!-- End Header -->

coworking/offersapp/templates/offersapp/includes/inc_js.html
{% load static %}
  <!-- Vendor JS Files -->
  <script src="{% static 'offersapp/assets/vendor/apexcharts/apexcharts.min.js' %}"></script>
<!--  <script src="{% static 'offersapp/assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>-->
  <script src="{% static 'offersapp/assets/vendor/bootstrap/js/bootstrap.js' %}"></script>
<!--  <script src="{% static 'offersapp/assets/vendor/bootstrap/js/bootstrap.min.js' %}"></script>-->
  <script src="{% static 'offersapp/assets/vendor/chart.js/chart.min.js' %}"></script>
  <script src="{% static 'offersapp/assets/vendor/echarts/echarts.min.js' %}"></script>
  <script src="{% static 'offersapp/assets/vendor/quill/quill.min.js' %}"></script>
  <script src="{% static 'offersapp/assets/vendor/simple-datatables/simple-datatables.js' %}"></script>
  <script src="{% static 'offersapp/assets/vendor/tinymce/tinymce.min.js' %}"></script>
  <script src="{% static 'offersapp/assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Yandex maps-->
  <script src="https://api-maps.yandex.ru/2.1?apikey=fe838c94-89e2-4657-a2ef-061f23ff1a53&lang=ru_RU" type="text/javascript"></script>
<!--  <script src="{% static 'offersapp/assets/js/offersapp_maps.js' %}" type="text/javascript"></script>-->
  <script src="{% static 'offersapp/assets/js/script.js' %}" type="text/javascript"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'offersapp/assets/js/main.js' %}"></script>

coworking/offersapp/templates/offersapp/includes/inc_paginator.html
<ul class="pagination justify-content-center">
    {% if object_list.has_previous %}
    <li class="page-item">
        <a class="page-link"
           href="{% url 'offers:page' object_list.previous_page_number %}?{{last_question}}">
            <
        </a>
    </li>
    {% endif %}
    <li class="page-item">
        <span class="page-link">
            страница {{ object_list.number }} из
            {{ object_list.paginator.num_pages }}
        </span>
    </li>

    {% if object_list.has_next %}
    <li>
        <a class="page-link"
           href="{% url 'offers:page' object_list.next_page_number %}?{{last_question}}">
            >
        </a>
    </li>
    {% endif %}
</ul>