coworking/authapp/urls.py
from django.contrib import admin
from django.urls import path
from authapp.views import login, user_logout, UserRegisterView, choose_type, landlord_register, verify

app_name = 'authapp'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', user_logout, name='logout'),
    path('choose/', choose_type, name='choose_type'),
    path('user/', UserRegisterView.as_view(), name='user'),
    path('landlord/', landlord_register, name='landlord'),
    path('verify/<email>/<activation_key>/', verify, name='verify'),
]

coworking/detailsapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from detailsapp.views import show_details, create_rental, add_favorite, send_review, get_available_seats, del_favorite

urlpatterns = [
    path('<int:pk>/', show_details, name='details'),
    path('add_fav/<int:pk>/', add_favorite, name='add_favorite'),
    path('del_fav/<int:pk>/', del_favorite, name='del_favorite'),
    path('new_rent/<int:pk>/', create_rental, name='create_rental'),
    path('review/<int:pk>/', send_review, name='send_review'),
    path('<int:pk>/<str:start_date>/<str:end_date>/<int:seats>/',
         get_available_seats, name='get_seats')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coworking/mainapp/urls.py
from django.contrib import admin
from django.urls import path, include
from mainapp.views import main
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main, name='main'),
    path('user/', include(('userapp.urls', 'userapp'), namespace='user')),
    path('auth/', include(('authapp.urls', 'authapp'), namespace='auth')),
    path('offers/', include(('offersapp.urls', 'offersapp'), namespace='offers')),
    path('details/', include(('detailsapp.urls', 'detailsapp'), namespace='details')),
    path('feedback/', include(('feedbackapp.urls', 'feedbackapp'), namespace='feedback')),
    path('admin_staff/', include(('adminapp.urls', 'adminapp'), namespace='admin_staff')),
    path('create/', include(('createapp.urls', 'createapp'), namespace='create')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coworking/userapp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import user, user_profile, user_bookings, user_favorites, user_locations, claim_landlord
from .views import booking_history, users, change_ad


app_name = 'userapp'

urlpatterns = [
    path('', user, name='main'),
    path('profile/', user_profile, name='profile'),
    path('bookings/', user_bookings, name='bookings'),
    path('locations/', user_locations, name='locations'),
    path('favorites/', user_favorites, name='favorites'),
    path('landlord-application/', claim_landlord, name='landlord-application'),
    path('booking-history/', booking_history, name='booking_history'),
    path('users/<int:pk>', users, name='users'),
    path('change-ad/<int:pk>', change_ad, name='change_ad'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coworking/mainapp/forms.py
from django import forms
from django.forms import Form, TextInput


class SearchMainForm(Form):
    city = forms.CharField(label="Адрес",
                           required=True,
                           widget=TextInput(attrs={'id': 'suggest', 'class': 'form-control',
                                                   'placeholder': 'Город'}))

    date_from = forms.CharField(required=False, widget=forms.HiddenInput(attrs={'id': 'date-from'}))
    date_to = forms.CharField(required=False, widget=forms.HiddenInput(attrs={'id': 'date-to'}))

coworking/mainapp/views.py
from django.shortcuts import render, redirect

from createapp.models import Room, OfferImages
from detailsapp.models import OffersRatings
from mainapp.forms import SearchMainForm


def main(request):
    title = 'ЛОКАЦИЯ | Сервис для поиска коворкинга в России'

    has_query = len(request.GET) > 0

    if has_query:
        form = SearchMainForm(data=request.GET)
    else:
        form = SearchMainForm()
    offer_ratings = list(OffersRatings.objects.order_by('-summary_rating')[:3])
    rooms = list(map(lambda x: x.offer, offer_ratings))
    offer_images = OfferImages.objects.filter(room__in=rooms)

    room_data = {}

    for rating in offer_ratings:
        room_data[rating.offer] = {
            'rating': rating.summary_rating
        }

    for image in offer_images:
        room_data[image.room]['image'] = image.image

    context = {
        'title': title,
        'form': form,
        'room_data': room_data
    }
    if has_query and form.is_valid():
        return redirect('offers/search/?' + request.GET.urlencode())
    return render(request, 'mainapp/index.html', context)

coworking/mainapp/templates/mainapp/includes/inc_datepicker.html
{% load static %}
<script src="{% static 'mainapp/assets/js/moment.min.js' %}" type="text/javascript"></script>
<script src="{% static 'mainapp/assets/js/daterangepicker.min.js' %}" type="text/javascript"></script>
<link rel="stylesheet" href="{% static 'mainapp/assets/css/daterangepicker.css' %}">
<script src="{% static 'mainapp/assets/js/datepicker_init.js' %}" type="text/javascript"></script>

coworking/mainapp/templates/mainapp/includes/inc_footer.html
{% load static %}
<footer id="contact" class="footer action-lage bg-black p-top-80">
        <!--<div class="action-lage"></div>-->
        <div class="container" style="display: flex;">
            <div class="row">
                <div class="widget_area" style="display: flex;justify-content: space-between;">
                    <div class="col-md-3">
                        <div class="widget_item widget_about">
                            <h5 class="text-white">О нас</h5>
                            <p class="m-top-20">"ЛОКАЦИЯ" - сервис поиска помещений для коворкинга.
                                С нами вы легко сможете найти подходящее место для проведения рабочего дня, а также
                            разместить своё собственное объявление и предоставить ваше помещение для коворкинга.</p>
                            <div class="widget_ab_item m-top-30">
                                <div class="item_icon"><i class="fa fa-location-arrow"></i></div>
                                <div class="widget_ab_item_text">
                                    <h6 class="text-white">Адрес офиса</h6>
                                    <p>{{contact_data.first_address}}</p>
                                    <p>{{contact_data.second_address}}</p>
                                </div>
                            </div>
                            <div class="widget_ab_item m-top-30">
                                <div class="item_icon"><i class="fa fa-phone"></i></div>
                                <div class="widget_ab_item_text">
                                    <h6 class="text-white">Телефон :</h6>
                                    <p>{{contact_data.first_phone}}</p>
                                    <p>{{contact_data.second_phone}}</p>
                                </div>
                            </div>
                            <div class="widget_ab_item m-top-30">
                                <div class="item_icon"><i class="fa fa-envelope-o"></i></div>
                                <div class="widget_ab_item_text">
                                    <h6 class="text-white">Email Address :</h6>
                                    <p>{{contact_data.first_mail}}</p>
                                    <p>{{contact_data.second_mail}}</p>
                                </div>
                            </div>
                        </div><!-- End off widget item -->
                    </div>

                    <div class="col-md-3" style="display: flex;justify-content: space-around;width: 100%;">
                        <div class="widget_item widget_service sm-m-top-50">
                            <h5 class="text-white">Арендодателям</h5>
                            <ul class="m-top-10">
                                <li class="m-top-20"><a href="{% url 'user:profile' %}"><i class="fa fa-angle-right"></i> Личный кабинет</a></li>
                                <li class="m-top-20"><a href="{% url 'feedback:main' %}"><i class="fa fa-angle-right"></i> Обратная связь</a></li>
                                {% for question in for_landlords %}
                                  <li class="m-top-20">
                                      <a href="{{ question.get_absolute_url }}">
                                          <i class="fa fa-angle-right"></i>{{ question.name }}
                                      </a>
                                  </li>
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="widget_item widget_service sm-m-top-50">
                            <h5 class="text-white">Пользователям</h5>
                            <ul class="m-top-10">
                                <li class="m-top-20"><a href="{% url 'user:profile' %}"><i class="fa fa-angle-right"></i> Личный кабинет</a></li>
                                <li class="m-top-20"><a href="{% url 'feedback:main' %}"><i class="fa fa-angle-right"></i> Обратная связь</a></li>
                                {% for question in for_users %}
                                  <li class="m-top-20">
                                      <a href="{{ question.get_absolute_url }}">
                                          <i class="fa fa-angle-right"></i>{{ question.name }}
                                      </a>
                                  </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>

                    <div class="col-md-3">
                        <div class="widget_item widget_newsletter sm-m-top-50">
                            <div class="widget_brand m-top-40">
                                <a href="" class="text-uppercase">ЛОКАЦИЯ</a>
                                <p>Удобный и быстрый поиск помещений для коворкинга.</p>
                            </div>
<!--                            <ul class="list-inline m-top-30">-->
<!--                                <li>- <a href=""><i class="fa fa-facebook"></i></a></li>-->
<!--                                <li><a href=""><i class="fa fa-twitter"></i></a></li>-->
<!--                                <li><a href=""><i class="fa fa-linkedin"></i></a></li>-->
<!--                                <li><a href=""><i class="fa fa-google-plus"></i></a></li>-->
<!--                                <li><a href=""><i class="fa fa-behance"></i></a></li>-->
<!--                                <li><a href=""><i class="fa fa-dribbble"></i></a> - </li>-->
<!--                            </ul>-->

                        </div><!-- End off widget item -->
                    </div>
                </div>
            </div>
        </div>
    </footer>

coworking/mainapp/templates/mainapp/includes/inc_header.html
{% load static %}
<nav class="navbar navbar-default bootsnav navbar-fixed no-background white">
    <div class="container">
<!--        <div class="attr-nav">-->
<!--            <ul>-->
<!--                <li class=""><a href="#Search"><i class="fa fa-search"></i></a></li>-->
<!--            </ul>-->
<!--        </div>-->

        <!-- Start Header Navigation -->
        <div class="navbar-header">
<!--            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-menu">-->
<!--                <i class="fa fa-bars"></i>-->
<!--            </button>-->
            <a class="navbar-brand" href="{% url 'main' %}">
                <img src="{% static 'mainapp/assets/images/logo.png' %}" class="logo" alt="">
                <!--<img src="assets/images/footer-logo.png" class="logo logo-scrolled" alt="">-->
            </a>

        </div>
        <!-- End Header Navigation -->

        <!-- navbar menu -->
        <div class="collapse navbar-collapse" id="navbar-menu">
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                                {% if user.is_landlord %}
                                <li><a href="{% url 'create:main' %}">Предложить помещения</a></li>
                                {% endif %}
                {% endif %}


                <!--                <li><a href="{% url 'user:favorites' %}">Мои любимые локации</a></li>-->
                {% if user.is_authenticated %}
                <li><a href="{% url 'user:profile' %}">Личный Кабинет</a></li>
                {% if user.is_staff %}
                <li><a href="{% url 'admin_staff:main' %}">Админка</a></li>
                {% endif %}
                {% else %}
                <li><a href="{% url 'auth:login' %}">Войти</a></li>
                {% endif %}

                <!-- <li><a href="#product">Portfolio</a></li> -->
                <!--                <li><a href="#team">Наша команда</a></li>-->
                <li><a href="{% url 'feedback:main' %}">Обратная связь</a></li>

            </ul>
        </div><!-- /.navbar-collapse -->
    </div>


</nav>

coworking/mainapp/templates/mainapp/includes/inc_js.html
{% load static %}
<script src="{% static 'mainapp/assets/js/vendor/jquery-1.11.2.min.js' %}"></script>
<script src="{% static 'mainapp/assets/js/vendor/bootstrap.min.js' %}"></script>
<script src="{% static 'mainapp/assets/js/vendor/bootstrap.js' %}"></script>
<script src="{% static 'mainapp/assets/js/jquery.magnific-popup.js' %}"></script>
<script src="{% static 'mainapp/assets/js/jquery.easing.1.3.js' %}"></script>
<script src="{% static 'mainapp/assets/js/bootsnav.js' %}"></script>

<script src="{% static 'mainapp/assets/js/plugins.js' %}"></script>
<script src="{% static 'mainapp/assets/js/main.js' %}"></script>

coworking/mainapp/templates/mainapp/includes/inc_search.html
{% load static %}
{% include 'mainapp/includes/inc_yandex_map.html' %}
{% include 'mainapp/includes/inc_datepicker.html' %}

<script src="{% static 'mainapp/assets/js/ymaps_init_script.js' %}" type="text/javascript"></script>
<section id="Search" class="search bg-blue search_test">
    <div class="search_overlay"></div>
    <div class="container">
        <div class="main-block">
            <h1 class="text-uppercase text-white">
                Бронируем офисы для работы
            </h1>
            <h3 class="text-white">Найдите свой вариант для комфортной работы</h3>
            <form class=""
                  method="GET"
                  action="{% url 'main' %}"
                  novalidate>
                <div class="main-search-block">
                    <div class="col-md-12">
                        <div class="form-floating">
                            {{ form.city }}
                            <label for="suggest">Город или адрес</label>
                            {% if "city" in form.errors %}
                            <div class="alert alert-danger">
                                <strong>{{ form.errors.city }}</strong>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-floating">
                            <input type="text" id="date-range" placeholder="Даты" class="form-control">
                            <label for="date-range">Даты</label>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <button type="submit" class="btn btn-primary">Найти</button>
                    </div>
                </div>
                {{ form.date_from }}
                {{ form.date_to }}
            </form>
        </div>
</section>

coworking/mainapp/templates/mainapp/includes/inc_slider.html
{% load static %}
<script type="text/javascript">
    initDatePicker();
</script>
<section id="product" class="product text-center">
            <div class="container">
                <div class="main_product roomy-80">
                    <div class="head_title text-center fix">
                        <h2 class="text-uppercase text-black"> Самые популярные пространства 2022 года</h2>
                    </div>

                    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                        <!-- Wrapper for slides -->
                        <div class="carousel-inner" role="listbox">
                            <div class="item active">
                                <div class="container">
                                    <div class="row">
                                        {% for room, data in room_data.items %}
                                        <div class="col-sm-4">
                                            <div class="port_item xs-m-top-30">
                                                <div class="port_img">
                                                    <img src="{{ data.image.url }}" alt="" />
                                                    <div class="port_overlay text-center">
                                                        <a href="{{ data.image.url }}" class="popup-img">+</a>
                                                    </div>
                                                </div>
                                                <div class="port_caption m-top-20">
                                                     <a href="{% url 'details:details' room.pk %}" target="_blank">
                                                        <h5>{{ room.name }}</h5>
                                                        <h6>{{ room.address.city }}</h6>
                                                         <h5> Рейтинг <strong>{{ data.rating }}</strong></h5>
                                                     </a>
                                                </div>
                                            </div>
                                        </div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>

                        </div>
                </div><!-- End off row -->
            </div><!-- End off container -->
        </section><!-- End off Product section -->

coworking/mainapp/templates/mainapp/includes/inc_team.html
{% load static %}
<section id="team" class="team bg-grey fix">
    <div class="container">
        <div class="main_team roomy-80">
            <div class="head_title text-center fix">
                <h2 class="text-uppercase">Лучшие арендодатели</h2>
                <h5>Представляем вам 3 арендодателя с наивысшими оценками</h5>
            </div>

            <div id="team-slid" class="carousel slide carousel-fade" data-ride="carousel">
                <ol class="carousel-indicators">
                    {% for landlord, ratings in top_landlords.items %}
                    <li data-target="#team-slid" data-slide-to="{{forloop.counter0}}" class="{% if forloop.counter0 == 0 %}active{% endif %}"></li>
                    {% endfor %}
                </ol>

                <div class="carousel-inner" role="listbox">
                    {% for landlord, ratings in top_landlords.items %}
                    <div class="item {% if forloop.counter0 == 0 %}active{% endif %}">
                        <div class="container">
                            <div class="row">
                                <div class="col-sm-4">
                                    <div class="team_item team_skill">
                                        <div class="team_author">
                                            <h4><a href="{% url 'user:users' landlord.pk %}">{{landlord.first_name}} {{landlord.last_name}}</a></h4>
                                        </div>

                                        <div class="team_skill_title fix m-top-40 m-bottom-40">
                                            <h5>Рейтинги</h5>
                                        </div>

                                        <div class="skill_bar sm-m-top-50 m-top-20">
                                            {% for rating, evaluation in ratings.items %}
                                            <div class="teamskillbar clearfix m-top-50" data-percent="{{evaluation}}%">
                                                <h6 class="text-uppercase">{{rating.name}}</h6>
                                                <div class="teamskillbar-bar"></div>
                                            </div>
                                            {% endfor %}
                                        </div>

                                    </div>
                                </div>

                                <div class="col-sm-4">
                                    <div class="team_item xs-m-top-30">
                                        <div class="port_img">
                                            <img src="{% if landlord.avatar %}
                                            {{ landlord.avatar.url }}
                                            {% else %}
                                            {% static 'userapp/assets/img/profile-img.jpg' %}
                                            {% endif %}" alt="" style="width: 100%;"/>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-sm-4">
                                    <div class="team_item team_content xs-m-top-30">
                                        <h4>{{landlord.about}}</h4>

                                        <div class="divider"></div>

                                        <div class="team_socail">
                                            <h5>Контакты</h5>
                                            <label for="landlord_mail">Почта</label>
                                            <h4 id="landlord_mail">{{landlord.email}}</h4>
                                            <label for="landlord_phone">Телефон</label>
                                            <h4 id="landlord_phone">{{landlord.user_phone}}</h4>
<!--                                            <ul class="list-inline m-top-20">-->

<!--                                                <li><a href=""><i class="fa fa-facebook"></i></a></li>-->
<!--                                                <li><a href=""><i class="fa fa-twitter"></i></a></li>-->
<!--                                                <li><a href=""><i class="fa fa-linkedin"></i></a></li>-->
<!--                                                <li><a href=""><i class="fa fa-google-plus"></i></a></li>-->
<!--                                                <li><a href=""><i class="fa fa-behance"></i></a></li>-->
<!--                                                <li><a href=""><i class="fa fa-dribbble"></i></a></li>-->
<!--                                            </ul>-->
                                        </div>

                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>

            </div>
        </div>
    </div>
</section>

coworking/mainapp/templates/mainapp/includes/inc_yandex_map.html
{% load static %}
<!-- Yandex maps-->
<script src="https://api-maps.yandex.ru/2.1?apikey=fe838c94-89e2-4657-a2ef-061f23ff1a53&lang=ru_RU"
        type="text/javascript"></script>