coworking/adminapp/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

urlpatterns = [
    path('', main, name='main'),
    path('contact/', edit_contacts, name='contact'),
    #категории
    path('question-category/', question_category, name='question_category'),
    path('question-category/edit/<int:pk>/', category, name='category_edit'),
    path('question-category/add/', add_category, name='category_add'),
    path('question-category/delete/<int:pk>/', delete_category, name='category_delete'),
    #вопросы
    path('questions/<int:pk>/', questions, name='questions'),
    path('questions/<int:pk_cat>/edit/<int:pk>/', question_edit, name='questions_edit'),
    path('questions/add/<int:pk_cat>', question_add, name='question_add'),
    path('questions/<int:pk_cat>/delete/<int:pk>/', question_delete, name='question_delete'),
    #сообщения от пользователей
    path('message/', message, name='message'),
    path('message-get/<int:pk>/', get_message, name='message_get'),
    path('message-delete/<int:pk>/', delete_message, name='message_delete'),
    #объявления
    path('offers/', offers, name='offers'),
    path('offers-pre-moderation/', pre_moderation, name='pre_moderation'),
    path('offers-pre-moderation/<int:pk>', show_offers_details, name='pre_moderation_details'),
    path('offers-pre-moderation/active/<int:pk>', allow_publishing, name='allow_publishing'),
    path('offers-convenience-type/', convenience_type, name='convenience_type'),
    path('offers-convenience-type-add/', convenience_type_add, name='convenience_type_add'),
    path('offers-convenience-type-delete/<int:pk>', convenience_type_delete, name='convenience_type_delete'),
    path('offers-convenience-type-edit/<int:pk>', convenience_type_edit, name='convenience_type_edit'),
    path('offers-convenience/<int:pk>', convenience, name='convenience'),
    path('offers-convenience/add/<int:pk_conv>', convenience_add, name='convenience_add'),
    path('offers-convenience-edit/<int:pk_conv>/<int:pk>/', convenience_edit, name='convenience_edit'),
    path('offers-convenience-delete/<int:pk_conv>/<int:pk>/', convenience_delete, name='convenience_delete'),
    path('user-booking/', booking, name='booking'),
    # категории объявлений
    path('room-category/', room_category, name='room_category'),
    path('room-category-edit/<int:pk>', room_category_edit, name='room_category_edit'),
    path('room-category-add/', room_category_add, name='room_category_add'),
    path('room-category-delete/<int:pk>', room_category_delete, name='room_category_delete'),
    #пользователи
    path('users/', users, name='users'),
    path('users/active/<int:pk>', staff_edit, name='staff_edit'),
    path('user/<int:pk>/', user, name='user'),
    #арендодатели
    path('landlords/', landlords, name='landlords'),
    path('landlords-history/', landlords_history, name='landlords_history'),
    path('landlord-history/<int:pk>/', landlord_history, name='landlord_history'),
    path('landlord/<int:pk>', landlord, name='landlord'),
    path('landlord/claim_accept/<int:pk>', claim_accept, name='claim_accept'),
    path('landlord/claim_reject/<int:pk>', claim_reject, name='claim_reject'),
    # отзывы
    path('criterion/', criterion, name='criterion'),
    path('criterion/add/', criterion_add, name='criterion_add'),
    path('criterion/edit/<int:pk>', criterion_edit, name='criterion_edit'),
    path('criterion/delete/<int:pk>', criterion_delete, name='criterion_delete'),
]

coworking/authapp/urls.py
from django.contrib import admin
from django.urls import path
from authapp.views import login, user_logout, UserRegisterView, choose_type, landlord_register, verify

app_name = 'authapp'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', user_logout, name='logout'),
    path('choose/', choose_type, name='choose_type'),
    path('user/', UserRegisterView.as_view(), name='user'),
    path('landlord/', landlord_register, name='landlord'),
    path('verify/<email>/<activation_key>/', verify, name='verify'),
]

coworking/mainapp/urls.py
from django.contrib import admin
from django.urls import path, include
from mainapp.views import main
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main, name='main'),
    path('user/', include(('userapp.urls', 'userapp'), namespace='user')),
    path('auth/', include(('authapp.urls', 'authapp'), namespace='auth')),
    path('offers/', include(('offersapp.urls', 'offersapp'), namespace='offers')),
    path('details/', include(('detailsapp.urls', 'detailsapp'), namespace='details')),
    path('feedback/', include(('feedbackapp.urls', 'feedbackapp'), namespace='feedback')),
    path('admin_staff/', include(('adminapp.urls', 'adminapp'), namespace='admin_staff')),
    path('create/', include(('createapp.urls', 'createapp'), namespace='create')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coworking/adminapp/models.py
from django.db import models
from userapp.models import UserModel
# ===================================

from django.conf import settings
from django.db import models

# Create your models here.
from django.db.models.signals import post_save
from django.dispatch import receiver


class Claim(models.Model):
    user_id = models.OneToOneField(
        UserModel,
        on_delete=models.CASCADE
    )

    text = models.TextField(
        verbose_name='текст заявителя',
        blank=True,
    )

    created_at = models.DateTimeField(
        auto_now_add=True
    )

    is_active = models.BooleanField(
        verbose_name='активна',
        default=True)

    is_approved = models.BooleanField(
        verbose_name='одобрено',
        blank=True,
        null=True)

    def __str__(self):
        return f"{self.user_id.first_name} {self.user_id.last_name}"

    class Meta:
        verbose_name = 'Заявка на получение прав арендодателя'
        verbose_name_plural = 'Заявки на получение прав арендодателя'

coworking/adminapp/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404

from detailsapp.views import get_offer_context, RatingNames
from feedbackapp.models import *
from django.urls import reverse
from adminapp.forms import *
from django.contrib import messages
from django.contrib.auth.decorators import user_passes_test
from createapp.models import *
# from authapp.models import UserModel
from userapp.models import UserModel
from createapp.models import ConvenienceType, Convenience
from adminapp.models import Claim
from offersapp.views import get_offers
from detailsapp.models import CurrentRentals, CompletedRentals

from authapp.views import send_verify_mail


def check_admin(user):
    return user.is_superuser


def check_admin_staff(user):
    return user.is_staff


def add_images_info(rooms):
    offers_dict = {}
    for room in rooms:
        room_images = OfferImages.objects.filter(room=room)
        # room_images = [_ for _ in room_images]
        offers_dict[room] = room_images
    return offers_dict


# ==================================
""" НУЖНО ПИСАТЬ КОМЕНТАРИИ!!!! """


# ==================================


@user_passes_test(check_admin)
def user(request, pk):
    title = 'Админка - Пользователь'

    this_user = get_object_or_404(UserModel, pk=pk)

    context = {
        'title': title,
        'this_user': this_user
    }
    return render(request, 'adminapp/users/user.html', context)


@user_passes_test(check_admin_staff)
def booking(request):
    title = 'Админка - Истории бронирований'

    if request.method == 'POST':
        start = request.POST.get('start_date')
        end = request.POST.get('end_date')
        user_booking = CurrentRentals.objects.filter(start_date__range=[start, end]).filter(
            end_date__range=[start, end])
        user_booking_completed = CompletedRentals.objects.filter(start_date__range=[start, end]).filter(
            end_date__range=[start, end])
    else:
        user_booking = CurrentRentals.objects.all()
        user_booking_completed = CompletedRentals.objects.all()
    context = {
        'title': title,
        'user_booking': user_booking,
        'user_booking_completed': user_booking_completed
    }
    return render(request, 'adminapp/offers/booking.html', context)


@user_passes_test(check_admin_staff)
def landlord_history(request, pk):
    title = 'Админка - Арендодалели'

    claim_landlord = get_object_or_404(Claim, pk=pk)
    context = {
        'title': title,
        'claim_landlord': claim_landlord
    }
    return render(request, 'adminapp/landlords/landlord-history.html', context)


@user_passes_test(check_admin_staff)
def criterion_delete(request, pk):
    criterion_item = get_object_or_404(RatingNames, pk=pk)
    criterion_item.delete()
    return HttpResponseRedirect(reverse('admin_staff:criterion'))


@user_passes_test(check_admin_staff)
def criterion_edit(request, pk):
    title = 'Админка - Критерии'
    criterion_item = get_object_or_404(RatingNames, pk=pk)
    if request.method == 'POST':
        criterion_form = CriterionEditForm(request.POST, instance=criterion_item)
        if criterion_form.is_valid():
            criterion_form.save()
            return HttpResponseRedirect(reverse('admin_staff:criterion'))
        else:
            return HttpResponseRedirect(reverse('admin_staff:criterion'))
    else:
        criterion_form = QuestionCategoryEditForm(instance=criterion_item)
    context = {
        'title': title,
        'criterion_form': criterion_form
    }
    return render(request, 'adminapp/reviews/criterion-edit.html', context)


@user_passes_test(check_admin_staff)
def criterion_add(request):
    title = 'Админка - Критерии'
    if request.method == 'POST':
        criterion_form = CriterionEditForm(request.POST)
        if criterion_form.is_valid():
            criterion_form.save()
            return HttpResponseRedirect(reverse('admin_staff:criterion'))
        else:
            return HttpResponseRedirect(reverse('admin_staff:criterion'))
    else:
        criterion_form = QuestionCategoryEditForm()
    context = {
        'title': title,
        'criterion_form': criterion_form
    }
    return render(request, 'adminapp/reviews/criterion-edit.html', context)


@user_passes_test(check_admin_staff)
def criterion(request):
    title = 'Админка - Критерии'
    criterions = RatingNames.objects.all()
    context = {
        'title': title,
        'criterions': criterions
    }
    return render(request, 'adminapp/reviews/criterion.html', context)


@user_passes_test(check_admin_staff)
def claim_accept(request, pk):
    claim_landlord = get_object_or_404(Claim, pk=pk)
    user_ll = get_object_or_404(UserModel, pk=claim_landlord.user_id.pk)
    user_ll.is_landlord = True
    user_ll.save()
    send_verify_mail(user_ll)

    claim_landlord.is_active = False
    claim_landlord.is_approved = True
    claim_landlord.save()

    return HttpResponseRedirect(reverse('admin_staff:landlords'))


@user_passes_test(check_admin_staff)
def claim_reject(request, pk):
    claim_landlord = get_object_or_404(Claim, pk=pk)
    claim_landlord.is_active = False
    claim_landlord.is_approved = False
    claim_landlord.save()
    send_verify_mail(request.user.pk)
    return HttpResponseRedirect(reverse('admin_staff:landlords'))


# ===============================================================
@user_passes_test(check_admin_staff)
def landlord(request, pk):
    title = 'Админка - Арендодалели'

    claim_landlord = get_object_or_404(Claim, pk=pk)
    context = {
        'title': title,
        'claim_landlord': claim_landlord
    }
    return render(request, 'adminapp/landlords/landlord.html', context)


@user_passes_test(check_admin_staff)
def landlords(request):
    title = 'Админка - Арендодалели'
    claim_landlords = Claim.objects.filter(is_active=True)
    context = {
        'title': title,
        'claim_landlords': claim_landlords
    }
    return render(request, 'adminapp/landlords/landlords.html', context)


@user_passes_test(check_admin_staff)
def landlords_history(request):
    title = 'Админка - Арендодалели'
    claim_landlords = Claim.objects.filter(is_active=False)
    context = {
        'title': title,
        'claim_landlords': claim_landlords
    }
    return render(request, 'adminapp/landlords/landlords-history.html', context)


# ===============================================================

@user_passes_test(check_admin_staff)
def convenience_delete(request, pk_conv, pk):
    conv = get_object_or_404(Convenience, pk=pk)
    conv.delete()
    return HttpResponseRedirect(reverse('admin_staff:convenience', kwargs={'pk': pk_conv}))


@user_passes_test(check_admin_staff)
def convenience_edit(request, pk_conv, pk):
    title = 'Админка - F.A.Q.'
    conv = get_object_or_404(Convenience, pk=pk)
    if request.method == 'POST':
        conv_form = ConvenienceEditForm(request.POST, instance=conv)
        if conv_form.is_valid():
            conv_form.save()
            return HttpResponseRedirect(reverse('admin_staff:convenience', kwargs={'pk': pk_conv}))
        else:
            return HttpResponseRedirect(reverse('admin_staff:convenience', kwargs={'pk': pk_conv}))
    else:
        conv_form = ConvenienceEditForm(instance=conv)
    context = {
        'title': title,
        'conv': conv,
        'conv_form': conv_form
    }
    return render(request, 'adminapp/offers/convenience-edit.html', context)


@user_passes_test(check_admin_staff)
def convenience_add(request, pk_conv):
    title = 'Админка - Удобства'
    conv_type = get_object_or_404(ConvenienceType, pk=pk_conv)
    if request.method == 'POST':
        conv_form = ConvenienceEditForm(request.POST)
        if conv_form.is_valid():
            new_conv = Convenience()
            new_conv.convenience_type = conv_type
            new_conv.name = conv_form.cleaned_data["name"]
            new_conv.file_name = conv_form.cleaned_data["file_name"]
            new_conv.save()
            return HttpResponseRedirect(reverse('admin_staff:convenience', kwargs={'pk': pk_conv}))
        else:
            return HttpResponseRedirect(reverse('admin_staff:convenience', kwargs={'pk': pk_conv}))
    else:
        conv_form = ConvenienceEditForm()
    context = {
        'title': title,
        'conv_type': conv_type,
        'conv_form': conv_form
    }
    return render(request, 'adminapp/offers/convenience-edit.html', context)


@user_passes_test(check_admin_staff)
def convenience(request, pk):
    title = 'Админка - F.A.Q.'
    conv_type = get_object_or_404(ConvenienceType, pk=pk)
    conveniences = Convenience.objects.filter(convenience_type_id__pk=pk)
    context = {
        'title': title,
        'conv_type': conv_type,
        'conveniences': conveniences
    }
    return render(request, 'adminapp/offers/convenience.html', context)


@user_passes_test(check_admin_staff)
def convenience_type_edit(request, pk):
    title = 'Админка - Удобства'
    conv_type = get_object_or_404(ConvenienceType, pk=pk)
    if request.method == 'POST':
        convenience_type_form = ConvenienceTypeEditForm(request.POST, instance=conv_type)
        if convenience_type_form.is_valid():
            convenience_type_form.save()
            return HttpResponseRedirect(reverse('admin_staff:convenience_type'))
        else:
            return HttpResponseRedirect(reverse('admin_staff:convenience_type'))
    else:
        convenience_type_form = ConvenienceTypeEditForm(instance=conv_type)
    context = {
        'title': title,
        'conv_type': conv_type,
        'convenience_type_form': convenience_type_form
    }
    return render(request, 'adminapp/offers/convenience-type-edit.html', context)


@user_passes_test(check_admin_staff)
def convenience_type_delete(request, pk):
    conv_type = get_object_or_404(ConvenienceType, pk=pk)
    conv_type.delete()
    return HttpResponseRedirect(reverse('admin_staff:convenience_type'))

coworking/adminapp/templates/adminapp/edit_contact.html
{% extends 'userapp/base.html' %}
{% load static %}
   {% block content %}

  <!-- ======= Header ======= -->
  {% include 'userapp/includes/inc_header.html' %}

  <!-- ======= Sidebar ======= -->
  {% include 'adminapp/includes/inc_sidebar.html' %}

  <main id="main" class="main">
      <div class="card">
            <div class="card-body">
              <h5 class="card-title">Контакты</h5>

              <!-- Multi Columns Form -->
              <form action="" method="post" class="row g-3">
              {% csrf_token %}
                <div class="col-md-6">
                  <label for="inputFirstAddress" class="form-label">Первый адрес</label>
                    {{ message_form.first_address }}
<!--                  <input type="text" value="{{ contacts.first_address }}" name="first_address" class="form-control" id="inputFirstAddress">-->
                </div>
                <div class="col-md-6">
                  <label for="inputSecondAddress" class="form-label">Второй адрес</label>
                    {{ message_form.second_address }}
<!--                  <input type="text" value="{{ contacts.second_address }}" name="second_address" class="form-control" id="inputSecondAddress">-->
                </div>
                  <div class="col-md-6">
                  <label for="input_first_phone" class="form-label">Первый телефон</label>
                      {{ message_form.first_phone }}
<!--                  <input type="text" value="{{ contacts.first_phone }}" name="first_phone" class="form-control" id="input_first_phone">-->
                </div>
                <div class="col-md-6">
                  <label for="input_second_phone" class="form-label">Второй телефон</label>
                    {{ message_form.second_phone }}
<!--                  <input type="text" value="{{ contacts.second_phone }}" name="second_phone" class="form-control" id="input_second_phone">-->
                </div>
                  <div class="col-md-6">
                  <label for="first_mail" class="form-label">Первая почта</label>
                      {{ message_form.first_mail }}
<!--                  <input type="email" value="{{ contacts.first_mail }}" name="first_mail" class="form-control" id="first_mail">-->
                </div>
                <div class="col-md-6">
                  <label for="second_mail" class="form-label">Вторая почта</label>
                    {{ message_form.second_mail }}
<!--                  <input type="email" value="{{ contacts.second_mail }}" name="second_mail" class="form-control" id="second_mail">-->
                </div>
                  <div class="col-md-6">
                  <label for="working_days" class="form-label">Дни работы</label>
                      {{ message_form.working_days }}
<!--                  <input type="text" value="{{ contacts.working_days }}" name="working_days" class="form-control" id="working_days">-->
                </div>
                <div class="col-md-6">
                  <label for="Opening_hours" class="form-label">Часы работы</label>
                    {{ message_form.Opening_hours }}
<!--                  <input type="text" value="{{ contacts.Opening_hours }}" name="Opening_hours" class="form-control" id="Opening_hours">-->
                </div>

                <div class="text-center">
                  <button type="submit" class="btn btn-primary">Изменить</button>
                  <button type="reset" class="btn btn-secondary">Отмена</button>
                </div>
              </form><!-- End Multi Columns Form -->

            </div>
          </div>
  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  {% include 'userapp/includes/inc_footer.html' %}
        {% endblock %}
{% block js %}

  {% include 'userapp/includes/inc_js.html' %}
{% endblock %}

coworking/adminapp/templates/adminapp/faq-category.html
{% extends 'userapp/base.html' %}
{% load static %}
   {% block content %}

  <!-- ======= Header ======= -->
  {% include 'userapp/includes/inc_header.html' %}

  <!-- ======= Sidebar ======= -->
  {% include 'adminapp/includes/inc_sidebar.html' %}

  <main id="main" class="main">
      <table class="table table-dark">
                <thead>
                  <tr>
                    <th scope="col">id</th>
                    <th scope="col">Название</th>
                    <th scope="col">Изменить</th>
                    <th scope="col">Удалить</th>
                    <th scope="col">updated</th>
                    <th scope="col">created</th>
                  </tr>
                </thead>
                <tbody>
                {% for category in faq_category %}
                  <tr>
                    <th scope="row">{{ category.pk }}</th>
                    <td><a class="nav-link collapsed" href="{% url 'admin_staff:questions' category.pk %}">
                        {{ category.name }}
                    </a></td>
                      <td><a class="nav-link collapsed" href="{% url 'admin_staff:category_edit' category.pk %}">
                          <i class="ri-edit-fill"></i>
                      </a></td>
                    <td><button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#verticalycentered{{ category.pk }}">
<!--                        <a class="nav-link collapsed" href="{% url 'admin_staff:category_delete' category.pk %}">-->
                          <i class="bi-x-circle"></i>
<!--                      </a>-->
                    </button></td>
                    <td>{{ category.updated }}</td>
                      <td>{{ category.created }}</td>
                  </tr>

              <div class="modal fade" id="verticalycentered{{ category.pk }}" tabindex="-1">
                <div class="modal-dialog modal-dialog-centered">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title"><span class="badge bg-danger">ВНИМАНИЕ</span></h5>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                      Вы уверены что хотите удалить категорию {{ category.name }}?
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Отмена</button>
                        <a class="nav-link collapsed" href="{% url 'admin_staff:category_delete' category.pk %}">
                      <button type="button" class="btn btn-primary">Удалить</button>
                        </a>
                    </div>
                  </div>
              </div><!-- End Vertically centered Modal-->

            </div>

                {% endfor %}
                </tbody>
              </table>

      <a class="nav-link collapsed" href="{% url 'admin_staff:category_add' %}"><button type="button" class="btn btn-dark">
                          Добавить категорию
                      </button></a>
  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  {% include 'userapp/includes/inc_footer.html' %}
        {% endblock %}
{% block js %}

  {% include 'userapp/includes/inc_js.html' %}
{% endblock %}

coworking/adminapp/templates/adminapp/faq-questions.html
{% extends 'userapp/base.html' %}
{% load static %}
   {% block content %}

  <!-- ======= Header ======= -->
  {% include 'userapp/includes/inc_header.html' %}

  <!-- ======= Sidebar ======= -->
  {% include 'adminapp/includes/inc_sidebar.html' %}

  <main id="main" class="main">
      <table class="table table-dark">
                <thead>
                  <tr>
                    <th scope="col">id</th>
                    <th scope="col">Название</th>
                    <th scope="col">Изменить</th>
                    <th scope="col">Удалить</th>
                    <th scope="col">updated</th>
                    <th scope="col">created</th>
                  </tr>
                </thead>
                <tbody>
                {% for question in faq_question %}
                  <tr>
                    <th scope="row">{{ question.pk }}</th>
                    <td>{{ question.name }}</td>
                      <td><a class="nav-link collapsed" href="{% url 'admin_staff:questions_edit' faq_category.pk  question.pk %}">
                          <i class="ri-edit-fill"></i>
                      </a></td>
                    <td><button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#verticalycentered{{ question.pk }}">
                          <i class="bi-x-circle"></i>
                    </button></td>
                    <td>{{ question.updated }}</td>
                      <td>{{ question.created }}</td>
                  </tr>

              <div class="modal fade" id="verticalycentered{{ question.pk }}" tabindex="-1">
                <div class="modal-dialog modal-dialog-centered">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title"><span class="badge bg-danger">ВНИМАНИЕ</span></h5>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                      Вы уверены что хотите удалить вопрос "{{ question.name }}"?
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Отмена</button>
                        <a class="nav-link collapsed" href="{% url 'admin_staff:question_delete' faq_category.pk question.pk %}">
                      <button type="button" class="btn btn-primary">Удалить</button>
                        </a>
                    </div>
                </div>
              </div><!-- End Vertically centered Modal-->

            </div>

                {% endfor %}
                </tbody>
              </table>

      <a class="nav-link collapsed" href="{% url 'admin_staff:question_add' faq_category.pk %}"><button type="button" class="btn btn-dark">
                          Добавить вопрос
                      </button></a>
  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  {% include 'userapp/includes/inc_footer.html' %}
        {% endblock %}
{% block js %}

  {% include 'userapp/includes/inc_js.html' %}
{% endblock %}

coworking/adminapp/templates/adminapp/get-message.html
{% extends 'userapp/base.html' %}
{% load static %}
   {% block content %}

  <!-- ======= Header ======= -->
  {% include 'userapp/includes/inc_header.html' %}

  <!-- ======= Sidebar ======= -->
  {% include 'adminapp/includes/inc_sidebar.html' %}

  <main id="main" class="main">
      <section class="section">
      <div class="row align-items-top">
        <div class="col-lg-6">
            <div class="card">
            <div class="card-body">
              <h5 class="card-title">Имя: {{ message_active.name }}</h5>
              <h5 class="card-title">Email: {{ message_active.email }}</h5>
              <h5 class="card-title">Дата: {{ message_active.created }}</h5>
            </div>
          </div>
            <div class="card">
            <div class="card-body">
              <h5 class="card-title">Тема: {{ message_active.subject }}</h5>
              {{ message_active.message }}
            </div>
          </div>
            {% if message_active.is_active %}
            <a class="nav-link collapsed" href="{% url 'admin_staff:message_delete' message_active.pk %}"><button type="button" class="btn btn-primary">
            Отметить как прочитанное
            </button></a>
            {% endif %}
        </div></div></section>
  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  {% include 'userapp/includes/inc_footer.html' %}
        {% endblock %}
{% block js %}

  {% include 'userapp/includes/inc_js.html' %}
{% endblock %}

coworking/adminapp/templates/adminapp/index.html
{% extends 'userapp/base.html' %}
{% load static %}
   {% block content %}

  <!-- ======= Header ======= -->
  {% include 'userapp/includes/inc_header.html' %}

  <!-- ======= Sidebar ======= -->
  {% include 'adminapp/includes/inc_sidebar.html' %}

  <main id="main" class="main">
  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  {% include 'userapp/includes/inc_footer.html' %}
        {% endblock %}
{% block js %}

  {% include 'userapp/includes/inc_js.html' %}
{% endblock %}

coworking/adminapp/templates/adminapp/messages.html
{% extends 'userapp/base.html' %}
{% load static %}
   {% block content %}

  <!-- ======= Header ======= -->
  {% include 'userapp/includes/inc_header.html' %}

  <!-- ======= Sidebar ======= -->
  {% include 'adminapp/includes/inc_sidebar.html' %}

  <main id="main" class="main">
      <section class="section">
      <div class="row">
        <div class="col-lg-6">

          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Не прочитаные сообщения</h5>

              <!-- Default Table -->
              <table class="table">
                <thead>
                  <tr>
                    <th scope="col">Имя</th>
                    <th scope="col">Тема</th>
                    <th scope="col">Дата</th>
                  </tr>
                </thead>
                <tbody>
                {% for message in messages_active %}
                  <tr>
                    <td><a class="nav-link collapsed" href="{% url 'admin_staff:message_get' message.pk %}">
                        {{ message.name }}
                    </a></td>
                    <td>{{ message.subject }}</td>
                    <td>{{ message.created }}</td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
              <!-- End Default Table Example -->
            </div>
          </div>

          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Прочитанные сообщения</h5>

              <!-- Dark Table -->
              <table class="table table-dark">
                <thead>
                  <tr>
                    <th scope="col">Имя</th>
                    <th scope="col">Тема</th>
                    <th scope="col">Дата</th>
                  </tr>
                </thead>
                <tbody>
                  {% for message in messages_not_active %}
                  <tr>
                    <td><a class="nav-link collapsed" href="{% url 'admin_staff:message_get' message.pk %}">
                        {{ message.name }}
                    </a></td>
                    <td>{{ message.subject }}</td>
                    <td>{{ message.created }}</td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
              <!-- End Dark Table -->

            </div>
          </div>
        </div></div></section>
  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  {% include 'userapp/includes/inc_footer.html' %}
        {% endblock %}
{% block js %}

  {% include 'userapp/includes/inc_js.html' %}
{% endblock %}